### ISSUE TITLE
KeyError: 'alpha'

### ISSUE THREAD

**Issue by spurgelaurels** [dylanaraps/wal#65]
```
[~  daphne@selenity ]$ wal -i $HOME/Pictures/Wallpapers -o wal-set -a "alpha"
image: Using image /home/daphne/Pictures/Wallpapers/NyOoWOg.jpg
Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==1.2.2', 'console_scripts', 'wal')()
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 157, in main
    process_args(args)
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 121, in process_args
    colors_plain = colors.get(image_file, notify=not args.q)
  File "/usr/lib/python3.6/site-packages/pywal/colors.py", line 94, in get
    util.Color.alpha_num = colors["alpha"]
KeyError: 'alpha'
```

Recent upgrade in Arch python-pywal-git-1.2.2.r4.ge393203-1

Downgrade to python-pywal-1.2.2-1 works splendidly.  

Will investigate a bit further after a few morning meetings.

**Comment by dylanaraps** [comment]
Wrong repo and a duplicate issue. I’m aware of this.

**Comment by spurgelaurels** [comment]
Oops!!  My apologies

**Comment by dylanaraps** [comment]
np :P
